; Original SRT simulator dashboard. No CSP or wheel-specific software required.
[DISPLAY_0]
NAME=SRT_DASH_SCREEN
EMISSIVE=1.8,2.1,1.6
INTENSITY=1.0

[ITEM_0]
PARENT=SRT_DASH
POSITION=0.052,-0.012,-0.0125
TYPE=GEAR
SIZE=0.043
COLOR=8,12,8,255
INTENSITY=1
FONT=e92_big
VERSION=2
ALIGN=CENTER

[ITEM_1]
PARENT=SRT_DASH
POSITION=-0.028,0.009,-0.0125
TYPE=RPM
SIZE=0.015
COLOR=8,12,8,255
INTENSITY=1
FONT=e92_mid
VERSION=2
ALIGN=CENTER

[ITEM_2]
PARENT=SRT_DASH
POSITION=-0.028,-0.020,-0.0125
TYPE=SPEED
SIZE=0.017
COLOR=8,12,8,255
INTENSITY=1
FONT=e92_mid
VERSION=2
ALIGN=CENTER
UNITS=SYSTEM

[LED_0]
OBJECT_NAME=SRT_SHIFT_0
RPM_SWITCH=11000
EMISSIVE=0,40,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_1]
OBJECT_NAME=SRT_SHIFT_1
RPM_SWITCH=11500
EMISSIVE=0,40,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_2]
OBJECT_NAME=SRT_SHIFT_2
RPM_SWITCH=12000
EMISSIVE=0,40,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_3]
OBJECT_NAME=SRT_SHIFT_3
RPM_SWITCH=12500
EMISSIVE=0,40,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_4]
OBJECT_NAME=SRT_SHIFT_4
RPM_SWITCH=13000
EMISSIVE=40,25,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_5]
OBJECT_NAME=SRT_SHIFT_5
RPM_SWITCH=13500
EMISSIVE=40,25,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_6]
OBJECT_NAME=SRT_SHIFT_6
RPM_SWITCH=14000
EMISSIVE=50,0,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5

[LED_7]
OBJECT_NAME=SRT_SHIFT_7
RPM_SWITCH=14500
EMISSIVE=50,0,0
DIFFUSE=0.3
BLINK_SWITCH=14500
BLINK_HZ=5
