[DIFF_POWER]
SHOW_CLICKS=0
TAB=DRIVETRAIN
NAME=Diff power - provisional
MIN=0
MAX=100
STEP=5
POS_X=0
POS_Y=0
HELP=HELP_DIFF_POWER

[DIFF_COAST]
SHOW_CLICKS=0
TAB=DRIVETRAIN
NAME=Diff coast - provisional
MIN=0
MAX=100
STEP=5
POS_X=0
POS_Y=1
HELP=HELP_DIFF_COAST

[DIFF_PRELOAD]
SHOW_CLICKS=0
TAB=DRIVETRAIN
NAME=AC preload - unmeasured
MIN=0
MAX=75
STEP=5
POS_X=0
POS_Y=2
HELP=HELP_DIFF_PRELOAD

[GEARS]
USE_GEARSET=0

[GEAR_1]
RATIOS=srt_fixed_gear_1.rto
NAME=Gear 1 - fixed
POS_X=0.5
POS_Y=0
HELP=HELP_REAR_GEAR

[GEAR_2]
RATIOS=srt_fixed_gear_2.rto
NAME=Gear 2 - fixed
POS_X=0.5
POS_Y=1
HELP=HELP_REAR_GEAR

[GEAR_3]
RATIOS=srt_fixed_gear_3.rto
NAME=Gear 3 - fixed
POS_X=0.5
POS_Y=2
HELP=HELP_REAR_GEAR

[GEAR_4]
RATIOS=srt_fixed_gear_4.rto
NAME=Gear 4 - fixed
POS_X=0.5
POS_Y=3
HELP=HELP_REAR_GEAR

[GEAR_5]
RATIOS=srt_fixed_gear_5.rto
NAME=Gear 5 - fixed
POS_X=0.5
POS_Y=4
HELP=HELP_REAR_GEAR

[GEAR_6]
RATIOS=srt_fixed_gear_6.rto
NAME=Gear 6 - fixed
POS_X=0.5
POS_Y=5
HELP=HELP_REAR_GEAR

[FRONT_BIAS]
SHOW_CLICKS=0
TAB=GENERIC
NAME=Brake bias - front percent
MIN=60
MAX=85
STEP=0.5
POS_X=0.5
POS_Y=1
HELP=HELP_BRAKE_BIAS
